import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Header from "@/layout/header";
import MaxWidthWrapper from "@/components/molecules/max-width-wrapper";
import Provider from "@/layout/provider";
import Footer from "@/layout/footer";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='scroll-smooth' lang='en'>
      <body className={cn(inter.className, "antialiased")}>
        <Provider>
          <Header />
          <main className='pt-4 pb-14 sm:px-4  md:py-6 md:px-0 min-h-[50vh]'>
            <MaxWidthWrapper>{children}</MaxWidthWrapper>
          </main>
          <Footer />
        </Provider>
        <Toaster
          position='top-center'
          richColors
          toastOptions={{
            classNames: {
              title: "text-center",
            },
          }}
        />
      </body>
    </html>
  );
}
